name: BPChannels
author: BlocksParty
main: me.blocksparty.channels.Channels
version: 1.0
description: >
             BlocksParty Essentials.
commands:
  regional:
    description: The Regional Channels!
  world:
    description: The World Channels!
  trade:
    description: The Trade Channels!
  advice:
    description: The Advice Channels!
  ooc:
    description: The OfF Topic Channels!
  operators:
    description: The OP Channels!
  gm:
    description: The GM Channels!
  pm:
    description: The GM Channels!